# Generated by Django 3.0.5 on 2020-05-05 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car_company',
            field=models.CharField(choices=[('tata', 'Tata'), ('maruti', 'Maruti'), ('mahindra', 'Mahindra'), ('bmw', 'BMW')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='car_fuel',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('natural_gas', 'Natural Gas'), ('hydrogen', 'Hydrogen')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='car_year',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
    ]
